name: PHP Quality Assurance

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer:v2
          coverage: xdebug
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run Linter (PHP-CS-Fixer)
        run: composer lint
      - name: Run Static Analysis (PHPStan)
        run: composer analyse
      - name: Run PHPUnit (with coverage)
        run: vendor/bin/phpunit --coverage-html build/coverage
      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: build/coverage

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Simuler le déploiement en production
        run: |
          echo "Déploiement sur le serveur de production..."
          echo " Connexion via SSH..."
          sleep 2
          echo " Pull du code depuis le dépôt Git..."
          sleep 2
          echo " Lancement des migrations de base de données..."
          sleep 3
          echo "Déploiement terminé avec succès!"
